name: surpassbusinessalliance.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9401073339395225
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#eb955c'
    - '#1acdd1'
    - '#0c6a6a'
    - '#83c3c3'
  brandStrength: 0
  lightness: 0.6760349099058658
  saturation: 0.7447635864373296
  rhythmicContrast: 0.046090110670775175
purpose: []
